{{- define "common.sealedFileSecret.tpl" -}}
{{- range .Values.sealedFileSecrets }}
{{- $robustName := include "common.robustName" $.Release.Name }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ printf "%s-%s" $robustName .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
  {{- range $f := .filesToMount }}
    {{ $f.name }}: |-
      {{- if $f.source }}
      {{- $f.source | nindent 6 }}
      {{- end }}
      {{- if $f.sourcePath }}
      {{- $.Files.Get $f.sourcePath | nindent 6 }}
      {{- end }}
  {{- end }}
  template:
    metadata:
      name: {{ printf "%s-%s" $.Release.Name .name }}
      namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end -}}
